### ISSUE TITLE
Varta - A News Feed Analyser APP

### ISSUE THREAD

**Issue by apneduniya** [spheronFdn/sos-ai-bounty#10]
# Varta

## Submitter Information
- **Name:** Adarsh Gupta, **Email:** thatsmeadarshgupta@gmail.com

## Reward Address
0x17Ad46C3C8AF35c79995014173Bf263DD14d0A22

## Project Plan
My goal is to create a News Feed Analyser app which provides comprehensive summaries of the latest news from many news outlets based on user interests, leveraging open-source LLMs, ScrapeGraph AI, Spheron and tools like LangChain ️.

### My upcoming goal is to:
- Currently, it supports **14 news outlets** and **60 interests** which I want to extend to **30-40 news outlets** which is popular among the news/article readers.
- Currently, it uses **Llama3 8B** model and I want to add support for multiple open source models like **Llama3 70B**, **Mixtral-8 7B**, **Llama-3.1 8B** so that the users can choose freely.
- User can **chat with the news**, so if they have some doubts or unclear about somethings then the Chatbot can help them.
- Adding a **pricing/subscription model** and will charge users for _more frequent newsletters on email, using models other than default (Llama3 8B), rate limits in Chatbot_.

## Repository
https://github.com/apneduniya/varta

## Demo
- **Video Demo:** https://www.youtube.com/watch?v=OL2nFczDWso

## Setup Instructions
https://github.com/apneduniya/varta?tab=readme-ov-file#-steps-to-run

## Spheron Infrastructure Usage
Spheron played the crucial role in the deployment of this project. By leveraging Spheron's robust and scalable deployment platform, we ensured that both our server and open-source AI model is accessible and performant on mobile app.

## Checklist
- [x] Added appropriate bounty label
- [x] Provided all required information
- [x] Ensured demo links are working
- [x] Verified setup instructions are clear and complete

**Comment by rekpero** [comment]
@apneduniya, can you mention what open-source tool, library, and tech stack has been used on your project? also mentioned all the functionality that you have implemented.

**Comment by apneduniya** [comment]
I have mentioned the features in the `README.md` of the repository, but also mentioning here:
- 🗞️ Aggregate news from 14+ sources.
- 🔍 Analyze content from 60+ interests choosed by user.
- 📝 Concise and comprehensive summaries of the latest news.
- 📧 Email subscriptions with customizable frequency.
- 🔖 Bookmark news for later read.

The tech stack I have used are:
**React Native (Expo), FastAPI, Langchain, MongoDB, ScrapeGraph AI, Ollama Llama 8B, SMTP, Spheron and BS4**

**Comment by apneduniya** [comment]
@izrake https://www.youtube.com/watch?v=j0LiRiz2iXg
Video on how to deploy the backend on Spheron and  add the backend link in app to start it :)

**Comment by izrake** [comment]
Hey @apneduniya, this looks quite good. 

You have passed all the parameters of the bounty & happy to approve the 1500 USD for this work.

We will release the bounty amount on this address 0x17Ad46C3C8AF35c79995014173Bf263DD14d0A22

But before that, we will send you an email to confirm some KYC details. Please look out for it.

**Comment by apneduniya** [comment]
Thanks a lot sir, super excited to start my work on upcoming goals 💪
