### ISSUE TITLE
Education-AI : AI-powered educational assistant

### ISSUE THREAD

**Issue by Anandha-Vihari** [spheronFdn/sos-ai-bounty#12]
# Education-AI

## Submitter Information
- **Name:** Anandha, **Email:** viharianandha@gmail.com

## Reward Address
0x2F816E7C2dbBeaAE1F33d3F7963DD2f008C3B487

## Project Plan
Education AI is a sophisticated AI-powered educational assistant designed to redefine personalized learning. By utilizing advanced AI methodologies, it provides tailored course recommendations, engages learners in Socratic-style dialogues, and simulates real-world technical interviews. This project addresses critical challenges in scalable teaching assistance, adaptive learning, and skill-based career preparation.

## Repository
https://github.com/Anandha-Vihari/Education-AI

## Demo
- **App Link:** http://provider.cpu.gpufarm.xyz:20004/
- **Video Demo:** 

## Setup Instructions
https://github.com/Anandha-Vihari/Education-AI?tab=readme-ov-file#deploying-on-spheron

## Spheron Infrastructure Usage
I utilized Spheron Network's scalable infrastructure to run complex libraries like NVIDIA cublas-cu12, cudnn-cu12, and transformers, ensuring high performance and seamless deployment. Spheron’s platform enabled the efficient execution of AI/ML models powered by langchain, torch, and sentence-transformers, as well as real-time media processing with mediapipe and vosk. Additionally, data processing libraries such as numpy, pandas, and scikit-learn were seamlessly managed, while chromadb, chroma-hnswlib, and SQLAlchemy handled data storage. This infrastructure supported GPU-accelerated workloads, ensuring optimal performance for my resource-intensive tasks.

## Checklist
- [x] Added appropriate bounty label
- [x] Provided all required information
- [x] Ensured demo links are working
- [x] Verified setup instructions are clear and complete

**Comment by Anandha-Vihari** [comment]
@izrake @rekpero please review the project....

**Comment by izrake** [comment]
hey we have noticed that you are using the existing llm running on cloud versus using any open source model.

Apart from that we encourage folks to use the spheron in the code instead of just for using external deployment platform. I don't think this qualifies for the bounty reward. But we would love to give you gpu credits which you can use to lease the machines easily from the network.

**Comment by Anandha-Vihari** [comment]
@izrake What if I use a local LLM with Django instead? Apologies for using Streamlit—it literally took me two weeks to build this project. On the bright side, I got to learn about the Spheron Network!

**Comment by izrake** [comment]
we have released some test token for your testing https://spheron-devnet-eth.explorer.caldera.xyz/tx/0x77ef6bd318d8c4740f584494862cb00c0c02d1cbaf109edcf4c109382176f771
