### ISSUE TITLE
AI-Celebrity-Chatbot

### ISSUE THREAD

**Issue by Anandha-Vihari** [spheronFdn/sos-ai-bounty#13]
# [AI-Celebrity-Chatbot](https://github.com/Anandha-Vihari/AI-Celebrity-Chatbot)

## Submitter Information
- **Name:** [Anandha], **Email:** [viharianandha@gmail.com]

## Project Plan
My goal is to develop an AI Celebrity Chatbot that lets users engage in realistic, lifelike conversations with virtual versions of their favorite celebrities. By leveraging open-source technologies and AI models, the chatbot will mimic the unique speech patterns, vocabulary, and personality traits of well-known figures, offering an interactive and entertaining user experience.

### My Upcoming Goals  
1. **Expand Celebrity Library**: Add more celebrities from diverse domains like film, music, and sports.  
2. **Introduce Voice Features**: Implement text-to-speech for responses in celebrity-like voices.  
3. **Enhance Realism**: Fine-tune conversational tone, humor, and personality traits for authenticity.   
4. **Multilingual Support**: Enable interactions in languages like Spanish, French, and German.  

## Repository
https://github.com/Anandha-Vihari/AI-Celebrity-Chatbot

## Demo
- **Video Demo:** https://youtu.be/OaubTTv2ptg

## Setup Instructions
https://github.com/Anandha-Vihari/AI-Celebrity-Chatbot?tab=readme-ov-file#-installation-guide

## Spheron Infrastructure Usage
In my project, I used Spheron’s infrastructure to efficiently deploy complex AI models like Llama3, Gemma, and Mixtral. By leveraging Spheron’s scalable cloud platform, I could run these models on RTX 4090 GPUs without needing expensive local hardware. This approach allowed me to reduce costs while ensuring high performance. Spheron’s seamless integration with my Ollama backend also made managing the deployment straightforward. Overall, Spheron enabled reliable, cost-effective deployment of powerful AI models, ensuring smooth operation and excellent user experience.

## Checklist
- [x] Added appropriate bounty label
- [x] Provided all required information
- [x] Ensured demo links are working
- [x] Verified setup instructions are clear and complete

**Comment by izrake** [comment]
Hey @Anandha-Vihari 

Your application looks quite good around celebrity AI & is also working quite smoothly.

But we looked into your main branch & it's not up to date.

You have used localhost to get the models, but if you are deploying them on the spheron, the localhost query does not work. Do you need something, or are we right in our understanding?

Please ensure that the code submitted is up to the market with the MIT License and also in the repo, which is also missing.

**Comment by Anandha-Vihari** [comment]
@izrake Thank you for reviewing my bounty!

Can you please clarify which updates I need to push to the main/repo?

While localhost works in Docker, I assume it should work with Spheron as well.

I’ll apply the MIT license—anything else missing that needs attention?

**Comment by izrake** [comment]
hey @Anandha-Vihari 

The demo looks good. Also, if you might have seen that in the repo, we have mentioned that just for deploying the things on Spheron or for using GPUs from the network for compute purposes, you won't be eligible for the bounty.  Spheron must be integrated into the product for stables.

Since you started working on this before we made the update on the repo, we are excited to award you with $500 USDT

To claim this reward, please post it on x, LinkedIn, or Insta along with your project & video. Submit the links here & we will get the funds emitted from our side.
 
 Keep building & keep shipping; we are here to support you.

**Comment by Anandha-Vihari** [comment]
@izrake  Hey,here is my tweet : https://x.com/notevilnorgood/status/1870788841470324833

**Comment by izrake** [comment]
I would recommend checking the requirements in the note. 

Also, all the bounty categories do not mean all the amount will be given to a single participant; it had to spread out. 

Lemme know if the bounty is acceptable & we will process it

**Comment by Anandha-Vihari** [comment]
@izrake
I understand that the full bounty amount isn’t awarded to a single participant, but I believe this project fully meets the requirements outlined in the bounty. I was planning to use the reward to buy a Mac, but after learning that the bounty is only $500, I am somewhat disappointed. However, for the next project, I’ll focus on integrating the Spheron SDK and aim for a larger bounty.

Additionally, I’m looking for an internship at Spheron, specifically for junior roles, and would love to be a part of the organization. I’m eager to join and leverage my experience with Spheron’s infrastructure to help further enhance your projects.

Also, I realized I haven’t provided the bounty receiving address. Could you please clarify which blockchain or network will be used for the payout? Should I provide an Ethereum (EVM), Solana, or another address?..

**Comment by izrake** [comment]
we will be dispatching the stables on eth mainnet.

also around the internship, we don't have an open position at the moment, but we will be more than happy reach out to you once we open it.

**Comment by Anandha-Vihari** [comment]
@izrake 0x2F816E7C2dbBeaAE1F33d3F7963DD2f008C3B487

I would really appreciate it if you could consider increasing the bounty amount, as I made this project after reviewing the code from previous bounty project [Varta](https://github.com/apneduniya/varta), and this is the second project I've done for you🥹.

Regarding the internship, I am not looking for a traditional internship. I am willing to work for free because I just want to be a part of the Spheron team. I truly believe Spheron is the future.

**Comment by izrake** [comment]
Let's have a call sometime after Christmas.

Bounty amount released, thank you so much for participating & really appreciate your contributions

https://etherscan.io/tx/0x8e416f8d08f722f7da4b10b5d3e26dfba88670b5d63df12794979edab0ebbf38

**Comment by Anandha-Vihari** [comment]
@izrake Any updates? I’d love the opportunity to work with the Spheron Network.....
