### ISSUE TITLE
AI Inference MarketPlace(Maha AI Hub)

### ISSUE THREAD

**Issue by DeImOs-Sj** [spheronFdn/sos-ai-bounty#7]
**Name**:- Shlok Jagtap

**Email**:-shlokjagtap.0608@gmail.com

**Description:**

We are working on building the world's first decentralized AI marketplace within Telegram mini apps. This platform empowers users and developers to seamlessly access, trade, and deploy AI models in a secure, transparent, and community-driven environment.

**Project Overview:**

Our project aims to democratize AI technology by integrating a marketplace directly within Telegram, a widely used messaging platform. The marketplace leverages blockchain technology to ensure security, transparency, and decentralization, allowing anyone to harness the power of AI without specialized knowledge.

**Key Features:**

Decentralized Marketplace: Facilitates secure, transparent, and intermediary-free AI model trading.
Seamless Telegram Integration: Provides a user-friendly interface within Telegram mini apps for AI model access.
Blockchain Security: Guarantees the integrity of transactions through smart contracts and immutable records.
Community-Driven Governance: Enables users to participate in platform governance via decentralized voting mechanisms.

**Links**
Github Org:-https://github.com/AI-Inference-Org
Project Pitch:-https://www.canva.com/design/DAGOLMGrdlc/A7M7lwJTn_bo0VIbcVWl3g/edit?utm_content=DAGOLMGrdlc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
Project Demo Video:-https://youtu.be/ayiI8rdaf8M
Docker Image Repository=https://hub.docker.com/layers/shlok1234/spheronimage/spheron/images/sha256-d3de8a8b108deb7345d19a2ad15f38032cee2aa15166ce949c611dfb5ace4538?context=repo
Tech stack used :- Docker React Node Express Typescript Prisma Jotai

**Comment by rekpero** [comment]
I recommend you to read the general submission guideline and follow it end to end, there are some fields that are not mentioned in your submission issue - https://github.com/spheronFdn/sos-ai-bounty?tab=readme-ov-file#-general-submission-guidelines

**Comment by izrake** [comment]
Also, I can see you don't have a trail of commitments in the GitHub. If you don;t have a trail, your submission may be rejected straightforwardly. Because we want to ensure the devs who are working on it & ensuring all the guidelines are eligible for the price pool.

**Comment by DeImOs-Sj** [comment]
> Also, I can see you don't have a trail of commitments in the GitHub. If you don;t have a trail, your submission may be rejected straightforwardly. Because we want to ensure the devs who are working on it & ensuring all the guidelines are eligible for the price pool.

I have the entire commit history you can check out or reach harpreet for confirmation the project was approved by him in the meet-up

**Comment by nanamikato** [comment]
@rekpero , I'm also working on the AI Marketplace bounty. Could you clarify whether the full $5,000 bounty will be awarded to a single winner, or will it be divided among the top projects if there are multiple outstanding submissions for the AI Marketplace project?

**Comment by DeImOs-Sj** [comment]
> Because we want to ensure the devs who are working on it & ensuring all the guidelines are eligible for the price pool.

Just checkout the details i have made the changes as per mentioned

**Comment by izrake** [comment]
> @rekpero , I'm also working on the AI Marketplace bounty. Could you clarify whether the full $5,000 bounty will be awarded to a single winner, or will it be divided among the top projects if there are multiple outstanding submissions for the AI Marketplace project?

Bounties are the pools from which devs can claim up to that amount given the novelty & design of the solution

**Comment by izrake** [comment]
> > Also, I can see you don't have a trail of commitments in the GitHub. If you don;t have a trail, your submission may be rejected straightforwardly. Because we want to ensure the devs who are working on it & ensuring all the guidelines are eligible for the price pool.
> 
> I have the entire commit history you can check out or reach harpreet for confirmation the project was approved by him in the meet-up ![image](https://private-user-images.githubusercontent.com/115064345/360005048-63542d47-e708-414e-9d1e-ff553e408605.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNjMzNzQsIm5iZiI6MTcyNDI2MzA3NCwicGF0aCI6Ii8xMTUwNjQzNDUvMzYwMDA1MDQ4LTYzNTQyZDQ3LWU3MDgtNDE0ZS05ZDFlLWZmNTUzZTQwODYwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxNzU3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTg4Njg0MWNlMzQ5NGRlZjFmODJhMTc5Y2IwNmRjNTU4NzI3NzBiYmQyZWJlNzVjYzBmNGM2MjkzODExZmY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JdlmwcRIX5pL3_p6nSDqlWXzAtuitjd9HJLeB8Bgt7E)

This is not accepted if the commits are not made on the single repo. https://github.com/AI-Inference-Org

The repo submitted has no trace of commits & also not able to validate how long you have been working on this one. Can you please provide a detailed overview around the same.

**Comment by izrake** [comment]
https://github.com/AI-Inference-Org - I can still see not proper readme & licenses are added. Please take your time & rectify everything. If we don't find the trace, this submission will be disqualified for the submissions.
