### ISSUE TITLE
MAHA AI HUB Decentralized AI Marketplace within Telegram Mini Apps

### ISSUE THREAD

**Issue by DeImOs-Sj** [spheronFdn/sos-ai-bounty#8]
# MAHA AI HUB Decentralized AI Marketplace within Telegram Mini Apps

## Submitter Information
- **Name:** Shlok Jagtap, **Email:** shlokjagtap.0608@gmail.com

## Reward Address
0xaE25777C98EE8a66b6A9D5243f3a92455A810ecF

## Project Plan
We are working on building the world's first decentralized AI marketplace within Telegram mini apps. This platform empowers users and developers to seamlessly access, trade, and deploy AI models in a secure, transparent, and community-driven environment.

## Repository
**Github Org:** [AI Inference Org](https://github.com/AI-Inference-Org)
## Demo
- **App Link:** [URL to the live demo ](https://maha-ai-hub-frontend.vercel.app/)
- **Video Demo:** [URL to a video demonstration ](https://youtu.be/ayiI8rdaf8M)

### Prerequisites
- Ensure you have Docker installed on your machine.
- Ensure you have Node.js and npm installed.

### Backend Setup
1. **Run Docker:**
   - Navigate to the project directory.
   - Run the following command to start the necessary Docker containers:
     ```bash
     docker-compose up
     ```

2. **Run Migrations:**
   - After Docker containers are up and running, apply Prisma migrations to set up the database schema:
     ```bash
     npx prisma migrate dev
     ```

3. **Start the Backend Server:**
   - Once migrations are applied, start the backend server:
     ```bash
     npm run dev
     ```

### Frontend Setup
1. **Install Dependencies:**
   - In the project directory, install the required dependencies:
     ```bash
     npm install
     ```

2. **Start the Frontend Server:**
   - Run the following command to start the frontend development server:
     ```bash
     npm run dev
     ```
## Spheron Infrastructure Usage
We have utilized Spheron's infrastructure to deploy the AI model for our decentralized marketplace. By leveraging Spheron's robust and scalable deployment platform, we ensured that our AI model is accessible and performant within the Telegram mini apps environment. 

For deployment, we used a Docker setup to containerize the application, and the following `docker-compose.yml` file was used to streamline the deployment process on Spheron:

You can refer to this docker image :- [docker compose yml file ](https://github.com/AI-Inference-Org/Chat_Model/blob/main/docker-compose.yml)

Docker image repository =  [Docker image repo link](https://hub.docker.com/layers/shlok1234/spheronimage/spheron/images/sha256-d3de8a8b108deb7345d19a2ad15f38032cee2aa15166ce949c611dfb5ace4538?context=repo)

**Comment by DeImOs-Sj** [comment]
Commit history trail 
![image](https://github.com/user-attachments/assets/e6b04df7-9b01-4be5-9de0-256c977217dd)

**Comment by izrake** [comment]
Hey, Thank you for creating the issue again.

We are still not able to understand where you are using GPUs. 

YAML attached is for the CPUs and models which are deploying it the raw one without any optimization into it. The steps of deploying on Spheron is also not present.

**Comment by izrake** [comment]
Since we have not received any response here for a month. We will wait for some more day & will clean this PR

**Comment by rekpero** [comment]
Closing this submission as there is been a long time of inactivity
